version: '3.7'
services:

  demo:
    build: ./demo
    labels:
      - "traefik.frontend.rule=Host:demo.${HOST:-docker.localhost}"
      - "traefik.port=80"
    volumes:
      - ./demo:/usr/share/nginx/html
  
  server:
    environment:
      - "REGISTRY_WHITELIST=^heymp\/,^rocker\/,^elmsln\/"
      - "CORS_ORIGIN=docker.localhost"

  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.10
    labels:
      - "traefik.frontend.rule=Host:hasura.${HOST:-docker.localhost}"
      - "traefik.port=8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgresql://prisma:prisma@postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey