version: '3.7'
services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      # - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  server:
    build: ./server
    labels:
      - "traefik.frontend.rule=Host:cod.${HOST:-docker.localhost}"
      - "traefik.port=3000"
    command: 'npm start'
    environment:
      - PRISMA_DB_PROVIDER=postgresql
      - PRISMA_DB_URL=postgresql://prisma:prisma@postgres
      - "REGISTRY_WHITELIST=^heymp\/,^rocker\/,^elmsln\/"
      - COD_AUTH_REQUIRED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # connect docker to the host machine docker thread
      - /usr/local/bin/docker:/usr/bin/docker # give the container access to docker
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
    depends_on:
      - postgres

  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - /var/lib/postgresql/data
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.port=5432"