version: '3.7'
services:

  demo:
    build: ./demo
    labels:
      - "traefik.frontend.rule=Host:demo.${HOST:-docker.localhost}"
      - "traefik.port=80"
    volumes:
      - /app/config.js
      - ./demo:/app
    environment:
      - "CONFIG_VARS=CONTAINERS_ON_DEMAND_ENDPOINT,CONTAINERS_ON_DEMAND_ORIGINS"
      - "CONTAINERS_ON_DEMAND_ENDPOINT=${HOST:-http://docker.localhost}"
      - "CONTAINERS_ON_DEMAND_ORIGINS=${ORIGINS:-http://demo.docker.localhost}"