version: '3.7'
services:

  demo:
    build: ./demo
    labels:
      - "traefik.frontend.rule=Host:demo.${HOST:-docker.localhost}"
      - "traefik.port=80"
    volumes:
      - ./demo:/app
    env_file: 
      - .env